name: conf-buildx

on:
  workflow_dispatch:
  push:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: clone https://github.com/heywoodlh/conf
        uses: actions/checkout@master
        with:
          name: heywoodlh/conf 
          repository: heywoodlh/conf 
          path: ./conf
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get conf version
        id: version
        run: echo "::set-output name=version::$(git -C ./conf rev-parse HEAD)"
      -
        name: Build and push heywoodlh/conf
        uses: docker/build-push-action@v2
        with:
          context: ./conf
          file: ./conf/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: heywoodlh/conf:latest,heywoodlh/conf:${{ steps.version.outputs.version }}
